### ISSUE TITLE
Permissions for administrative operations (pause/admin) should be more granular.

### ISSUE THREAD

**Issue by joeabbey** [strangelove-ventures/hyperlane-cosmos#40]
The solidity contracts allows the contract "owner" to pause and/or admin the contracts.

Currently these are attribute on methods with the underlying storage or an "owner/admin" in place.

Hyperlane wishes to make these permissions more granular:
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2054

In cosmos, we have the authz module, and so it may be possible to simply create new grants for operations like pause.

**Comment by jonathanpberger** [comment]
@agouin thinks this may be out of scope for MVP. Chat w/ them and find out.

**Comment by yorhodes** [comment]
> @agouin thinks this may be out of scope for MVP. Chat w/ them and find out.

agreed this is not strictly necessary

**Comment by akc2267** [comment]
this is a low priority optimization ticket

**Comment by misko9** [comment]
Closing as out-of-scope for MVP. Will re-open, if and when necessary.
