### ISSUE TITLE
E2E test: `interchaintest`: Cosmos <-> Cosmos data transfer

### ISSUE THREAD

**Issue by jonathanpberger** [strangelove-ventures/hyperlane-cosmos#47]
This test should use the Hyperlane relayer to relay a message between two [`hyperlane-simd`](https://github.com/strangelove-ventures/hyperlane-cosmos/tree/main/cmd/simd) cosmos based chains.

Brainstorm:
 - Go relayer not needed
 - No need to initially build out "Hyperlane" relayer interface in interchaintest. Run relayer as a binary from localhost.
 - Potentially leverage spinning relayer in "sidecar" process: https://github.com/strangelove-ventures/interchaintest/pull/465

**Comment by akc2267** [comment]
remaining component: IGP
