### ISSUE TITLE
Produce  hyperlane validator/relayer docker image

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/hyperlane-cosmos#52]
Evaluate whether image should be built as a Dockerfile, or potentially integrated into the hyperlane simd image (change `dockerfile: cosmos` to `dockerfile: cargo` and modify build steps)

AC: container image on ghcr

**Comment by misko9** [comment]
My recommendation is for the hyperlane agents to have their own docker image. This for a few reasons, one being there are two separate repos and another, to keep each slimmer, faster to compile and not adding additional bloat to the cargo dockerfiles.
Heighliner PR for hyperlane-agents can be found here: https://github.com/strangelove-ventures/heighliner/pull/168
